.PHONY: clean All

All:
	@echo "==========Building project:[ ejemplo001 - Debug ]=========="
	@cd "ejemplo001" && "$(MAKE)" -f  "ejemplo001.mk"
clean:
	@echo "==========Cleaning project:[ ejemplo001 - Debug ]----------"
	@cd "ejemplo001" && "$(MAKE)" -f  "ejemplo001.mk" clean
